### ISSUE TITLE
Table.ToCSharpCode(DataTable) writes empty files

### ISSUE THREAD

**Issue by DigitalLibrarian** [AdamRakaska/EntityJustworks#1]
I have tried a number of different DataTables (with data) and in each case this method only creates 0 byte files.  Also, it would be very nice if I could invoke that without the hard-disk dependency.

**Comment by AdamWhiteHat** [comment]
This issue has been resolved.  Please grab the latest version of the code from either branch and rebuild.

This issue was caused by improperly reading the MemoryStream in Code.cs, line # 43; Encoding.ASCII.GetString(ms.ToArray()) was not working as expected.
To fix the issue, I flushed the TextWriter to ensure that any/all buffered data was written to the underlying MemoryStream, I set the memoryStream.Position to zero, then I opened up a StreamReader and called the ReadToEnd method to read the data written to the MemoryStream.
